# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

cache:
  paths:
  - vendor/
before_script:
    # Install git (the php image doesn't have it) which is required by composer
    - apt-get update -yqq
    - apt-get install git -yqq
    # Install composer dependencies
    - curl --silent --show-error https://getcomposer.org/installer | php
    - php composer.phar install
    - find . -type d | grep .git | xargs rm -rf

stages:
  - deploy

release-zip:
  stage: deploy
  environment: production
  script:
    - ls -la
    - chown -R www-data:www-data .
    - php -r '$infoFile = json_decode(file_get_contents("info.json")); $infoFile->version = $argv[1]; $infoFile->last_update = $argv[2]; file_put_contents("info.json", json_encode($infoFile, JSON_PRETTY_PRINT));' -- "$CI_BUILD_TAG" "$(date)"
  artifacts:
    name: "$CI_BUILD_TAG"
    paths:
        - 404/
        - classes/
        - config/
        - glancr/
        - locale/
        - modules/
        - reset/
        - vendor/
        - wlanconfig/
        - cron.php
        - index.php
        - info.json
        - nonet.php

  only:
    - tags