# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

cache:
  paths:
  - vendor/

before_script:
  # Install git (the php image doesn't have it) which is required by composer
  - apt-get update -yqq
  - apt-get install git -yqq
  # Install composer dependencies
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install

stages:
  - deploy

deploy-zip:
  stage: deploy
  script:
    - pwd
  artifacts:
      paths:
      - $CI_BUILD_TAG.zip
#  only:
#    - tags

# Builds a complete Raspbian image if there's a new tag in the repo.
#run-build:
#  stage: deploy-image
#  script:
#    - sudo apt-get install xserver-xorg xinit mc matchbox unclutter fbi midori x11-xserver-utils mysql-server apache2 phpMyAdmin php5-curl hostapd dnsmasq
#  only:
#    - tags

