# Select image from https://hub.docker.com/r/_/php/
image: php:5.6

before_script:
# Install dependencies
- pwd()
- bash /builds/glancr/system/ci/docker_install.sh > /dev/null
# Install composer dependencies
- curl --silent --show-error https://getcomposer.org/installer | php
- php composer.phar install

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

stages:
  - deploy

deploy-zip:
  stage: deploy
  script:
    - zip $CI_BUILD_TAG .
  artifacts:
      paths:
      - target/*.zip
#  only:
#    - tags

# Builds a complete Raspbian image if there's a new tag in the repo.
#run-build:
#  stage: deploy-image
#  script:
#    - sudo apt-get install xserver-xorg xinit mc matchbox unclutter fbi midori x11-xserver-utils mysql-server apache2 phpMyAdmin php5-curl hostapd dnsmasq
#  only:
#    - tags

